<form action="index.php" method="post">
    
    <fieldset>
        <label>Email</label>
        <input type="email" name="newUserEmail"/>
    </fieldset>
    <fieldset>
        <label>Nom</label>
        <input type="text" name="newUserUsername"/>
    </fieldset>
    <fieldset>
        <label>Password</label>
        <input type="password" name="newUserPassword"/>
    </fieldset>
    <input type="hidden" name="formName"/>
    <input type="submit" value="Créer l'utilisateur"/>

</form>