<form action="index.php" method="post">
    
    <fieldset>
        <label>Email</label>
        <input type="email" name="editUserEmail"/>
    </fieldset>
    <fieldset>
        <label>Nom</label>
        <input type="text" name="editUserUsername"/>
    </fieldset>
    <fieldset>
        <label>Password</label>
        <input type="password" name="editUserPassword"/>
    </fieldset>
    <input type="hidden" name="formName"/>
    <input type="submit" value="Modifier l'utilisateur"/>

</form>