<table>
    <thead>
        <tr>
            <th>Email</th>
            <th>Utilisateur</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach($data["users"] as $user){
        ?> 
        <tr>
            <td><?php echo $user->getEmail(); ?></td>
            <td><?php echo $user->getUsername(); ?><td>
        </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<?php

?>